chihacknight/decarbonize-my-state

- src/components/choroplethmap.js
- src/components/state-details.js
- src/styles/global.css
Create the basic layout of the state details page, based on the [related mocks](https://app.moqups.com/pcSQvUMmsyAa1SN58KaKg1EKuYRs8iRX/view/page/a97a1436c).
This includes all of the text and the proper emissions by category % figures for each state, but does not include any new graphs or images. I also didn't add placeholders for every single image since that feels overkill and the layout could change depending on the images we end up going with.
Closes #20.
| Intro | First Section |
| --- | --- |
| ![Screenshot from 2022-03-13 16-11-36](https://user-images.githubusercontent.com/3187531/158079457-5bdbdc50-78c1-4abc-9d9a-b17b35690296.png) | ![Screenshot from 2022-03-13 16-11-49](https://user-images.githubusercontent.com/3187531/158079461-e710cece-8ea5-4a0f-89b3-502581d1ce5c.png) |
I was …
> State Details Page Layout

- src/components/singlebar.js
- src/pages/index.js
Small PR to clean up the code from #36 and place it in the proper place on the home page
Closes #18 
* confirm the single stacked bar chart renders as expected on the home page
> cleanup the single bar component

- gatsby-config.js
- src/components/choroplethmap.js
- src/components/simpleareachart.js
- src/components/singlebar.js
- src/pages/index.js
- src/styles/global.css
- src/styles/index.css
Fixes mobile issues on the homepage and state details pages by making sure all graphs scale down to mobile properly and scaling a few large pieces of text.
<details>
<summary>Comparison</summary>
| Before | After |
| --- | --- |
| ![state-decarbonize netlify app_(iPhone SE) (2)](https://user-images.githubusercontent.com/3187531/164149143-c2b29342-e151-47c7-9093-547f19c4f808.png) | ![localhost_8000_(iPhone SE)](https://user-images.githubusercontent.com/3187531/164149140-70badba2-d78f-457f-8699-b19d272e811c.png) |
</details>
Closes #54.
See description.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* Test on mobile, tablet, and desktop
* Also make sure to drag around the width to confirm there's no views at which things look atrocious
* …
> Fix Mobile Styling

- src/components/simpleareachart.js
This PR solves the problem of bumpy graphs caused by rounding to the nearest whole integer.  The calculation is now set to calculate to the .01 which when graphed smooths out the bumps.
Closes #059
Optional. Screenshots, `curl` examples, etc.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
Visually inspect the state details graph for Maine to verify the graph is smooth.  Also check random states' graphs to verify no addition bugs have been introduced.
> graph is smooth

- src/components/choroplethmap.js
- src/pages/index.js
- src/styles/global.css
Makes it so the map of states on the homepage uses a Bootstrap tooltip and is now tabbable and shows the tooltip. Here's a little demo, starting with tabbing and then moving to using the mouse:
https://user-images.githubusercontent.com/3187531/167757160-03dd37bb-dd6e-43b4-bffa-7d791ac9c675.mp4
Closes #78
Optional. Screenshots, `curl` examples, etc.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* Try tabbing through the map and confirm you see the tooltips
* Hover over the map and confirm you see reasonable tooltipss
> Make state tooltip nice and tabbable

- src/styles/global.css
Increase contrast on navbar and action-panel links for accessibility.
Closes #77 
I have made links in the following places less transparent, increasing the contrast.
axeDevTools no longer reports accessibility issues with the links when the full-site scan is run.
> accessibility: increase contrast on navbar and action-panel links

- src/components/AlreadyElectrifiedChart.js
- src/components/choroplethmap.js
- src/components/header.js
- src/components/state-details.js
- src/pages/404.js
- src/pages/about.js
- src/pages/index.js
- src/pages/terminology.js
- src/styles/global.css
Fixes some last accessibility issues, in particular:
1. Not being able to use the map on the homepage to navigate with just the keyboard (it was tabbable, but hitting Enter didn't navigate)
2. Not having a skip to main content link - you can now hit tab from the URL bar, hit Enter on the skip link, then hit tab to be on the first interactive element in the main content
3. Fixed a minor hold-over `aria-labelledby` attribute.
See the demo section for a better demo of the skip link.
This PR closes #91 and #90
| Homepage Skip Demo | State Details Skip Demo |
| --- | --- |
| ![Peek 2022-05-17 20-38](https://user-images.githubusercontent.com/3187531/168939672-45576f53-06b9-44b4-a6ea-7bcee33930e0.gif) | ![Peek 2022-05-17 20-39](https://user-images.githubusercontent.com/3187531/168939669-01a1fa11- …
> Accessibility Fixes 2 - Fix Homepage Map Keyboard Use & Add Skip to Main Link 

- gatsby-config.js
- src/components/seo.js
Debugging the Twitter social card which is missing the image preview. Requires Netlify build to be deployed in order for card to be generated. Testing removing a "/" in the image url, and adding an image:alt tag.
This resolves issue #96
To test, paste the link of the Netlify build here: 
https://cards-dev.twitter.com/validator
This is the fixed Twitter social card preview:
There is no regression using the Facebook card validator:
> debug twitter social card

- gatsby-config.js
- src/components/header.js
Removed header links to the empty terminology and about pages and added a basic beta notice.
| Desktop | Mobile (Home) | Mobile (State) 
| --- | --- | --- |
| ![Screenshot from 2022-05-24 21-50-10](https://user-images.githubusercontent.com/3187531/170169521-93684344-326d-4099-83da-47056b02c424.png) | ![Screenshot from 2022-05-24 21-50-19](https://user-images.githubusercontent.com/3187531/170169519-7c617a57-5315-45b5-b036-38802623173a.png) | ![Screenshot from 2022-05-24 21-51-53](https://user-images.githubusercontent.com/3187531/170169752-78ec1d76-f07d-41fa-8c36-04beb9608df9.png) |
See description.
None!
* Just checked mobile and desktop to make sure the notice looked good and the links were gone
> Remove Empty Page Header Links and Add Beta Notice

- src/pages/take-action.js
- src/styles/global.css
I have created a new page: /take-action within the application, and added the call-to-action copy from the google doc, as well as the google form within an iframe. I carried over the basic formatting/markup from the doc.
Closes #65 
Open to feedback on the styling.
> create take-action page with call to action copy and google form

- src/components/header.js
- src/components/state-details.js
- src/pages/index.js
- src/styles/global.css
Adds Take Action link to:
- header nav
- index page below the map
- state detail pages at the bottom
Removes beta banner since all links are now populated.
Related to #117 
* review the home page and state detail pages and confirm the take action section looks good
> add take action links

- src/components/state-details.js
- src/pages/index.js
Fixes mobile alignment of the Take Action link.
Before:
After: 
* view the site on mobile and confirm the take action button is positioned correctly
> better markup for mobile styling of take action link

- gatsby-config.js
I don't know why, but we had the wrong Google Tag Stream ID in our config. This PR fixes it.
* must be tested on production
> using proper Gtag stream ID

- gatsby-config.js
Google Analytics is still not working. This PR removes extra configuration from `gatsby-plugin-google-gtag`. I believe the `origin` was incorrectly configured.
I was able to successfully test this in the deploy preview using the Google Analytics Debugger: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en
Also, finally seeing data in Analytics:
* download and turn on the Google Analytics Debugger in Chrome: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en
* open the deploy preview and confirm the console output shows the debugger output. It should look like:
> gtag configuration (again)

- src/pages/index.js
Adds the word "It" to the homepage.
Closes #XXX
Just try it 😆 
None.
* Confirm homepage sentence looks good on mobile and desktop
> Fix Homepage Typo

- src/pages/take-action.js
- fixes a few typos on the take action page
- adds links for more info on heat pumps and induction stoves (same as state detail page)
* read through copy on take action and confirm changes
> typos and links on take action page

- src/components/state-details.js
- src/pages/about.js
- src/pages/take-action.js
This pull request updates the calculations we make counting cars and buildings to be electrified to account for the already electrified percentages. Slightly changes the order of the text and bar chart so we establish the percentage before we account for it in the annual count.
Additional changes:
* small spacing fixes for links on the about page
* updates link to Climate Cabinet to a custom ActBlue URL
Closes #127
**Buildings** 
before
after
**Cars**
before
after
* view the state detail pages and confirm the building and vehicle counts look accurate
* check states like Alaska and Hawaii that have no building electrification percentage info
* check the about page and confirm we don't have any links without spaces around them
> Annual Counts Fix for Vehicles & Buildings

- src/components/state-details.js
- src/pages/about.js
Fixed the NREL link pointing to a PDF that pointed to an updated PDF (now saving a user the redirect) and added a new short sentence about ditching cars:
I thought this was important to add because from an overall materials perspective bikes and public transit are much much more efficient, but they aren't an option for everyone, so I think making it a secondary mention is a good fit for this site. Basically I want it to read as "Have a car? You should switch to an EV, but consider other options too".
See description.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
Tested changed NREL Link and confirmed new text looks good on desktop and mobile.
> Fix Deprecated About Link and Add Car Free Note

- src/components/displayplants.js
- src/components/state-details.js
- src/styles/global.css
- src/styles/state-details.css
Fixes issues with my latest state details page, like tight spacing and duplicate images (which I think was caused by a React HTML error)
This also includes some improvements to the wording and spacing of the sections that say how much pollution is dropped. I made the text clarify _what_ dropped the emissions (more clear, more screen-shottable) and experimentally made them fade in for emphasis:
| Before | After |
| --- | --- |
|  ![Screenshot from 2022-08-28 21-31-43](https://user-images.githubusercontent.com/3187531/187112618-70fe2ee8-ef60-46f7-a028-b25533199093.png) | ![Screenshot from 2022-08-28 21-31-54](https://user-images.githubusercontent.com/3187531/187112854-d4aed1e8-3bc0-4a62-a6fa-2026c6ae6643.png) |
Fade In Text Demo:
**Note:** I just tacked in the fade in behavior. If folks …
> Fix State Details Page Rework Bugs

- src/components/choroplethmap.js
- src/components/state-details.js
- src/constants/source-citations.js
- src/pages/about.js
Adds "Source" citations to the home page map, as well as for the charts on the state detail pages.
Closes #132 
- view the home page and confirm you see the source below the map legend
- on the state detail page, confirm you see the source for emissions over time, the emissions breakdown on the left, and under each of the smaller bar charts for each section
- confirm it looks good on mobile as well
> source citation for charts

- src/components/state-details.js
- src/constants/terminology-list.js
- src/pages/faq.js
- src/styles/state-details.css
In one of my user interviews a user didn't know what an induction range is or what a heat pump was, and the Wikipedia links we used before were a bit much and take folks out of the flow. I moved these two appliances into the terminology list - here's a demo (the text has been updated since this GIF though):
Also fixed a bug where focusing the new terminology tooltips sometimes being off screen because of the double sticky header. You can test this by tabbing down to the wind power source (try clicking down on the link, moving your mouse off, and letting go of the mouse to move focus more quickly) and then using Shift + Tab to go back one tabbable element:
| Before | After |
| --- | --- |
| ![Screenshot from 2023-01-22 17-57-54](https://user-images.githubusercontent.com/3187531/213947547-0d …
> Add Tooltip for Induction Stoves & Heat Pumps
